do (moment) ->
  STRINGS =
    nodiff: ''
    year: 'year'
    years: 'years'
    month: 'month'
    months: 'months'
    day: 'day'
    days: 'days'
    hour: 'hour'
    hours: 'hours'
    minute: 'minute'
    minutes: 'minutes'
    second: 'second'
    seconds: 'seconds'
    delimiter: ' '

  moment.fn.preciseDiff = (d2) ->
    moment.preciseDiff this, d2

  moment.preciseDiff = (d1, d2) ->
    m1 = moment(d1)
    m2 = moment(d2)

    pluralize = (num, word) ->
      num + ' ' + STRINGS[word + (if num == 1 then '' else 's')]

    if m1.isSame(m2)
      return STRINGS.nodiff
    if m1.isAfter(m2)
      tmp = m1
      m1 = m2
      m2 = tmp
    yDiff = m2.year() - m1.year()
    mDiff = m2.month() - m1.month()
    dDiff = m2.date() - m1.date()
    hourDiff = m2.hour() - m1.hour()
    minDiff = m2.minute() - m1.minute()
    secDiff = m2.second() - m1.second()
    if secDiff < 0
      secDiff = 60 + secDiff
      minDiff--
    if minDiff < 0
      minDiff = 60 + minDiff
      hourDiff--
    if hourDiff < 0
      hourDiff = 24 + hourDiff
      dDiff--
    if dDiff < 0
      daysInLastFullMonth = moment(m2.year() + '-' + m2.month() + 1, 'YYYY-MM').subtract(1, 'M').daysInMonth()
      if daysInLastFullMonth < m1.date()
        # 31/01 -> 2/03
        dDiff = daysInLastFullMonth + dDiff + m1.date() - daysInLastFullMonth
      else
        dDiff = daysInLastFullMonth + dDiff
      mDiff--
    if mDiff < 0
      mDiff = 12 + mDiff
      yDiff--
    result = []
    if yDiff
      result.push pluralize(yDiff, 'year')
    if mDiff
      result.push pluralize(mDiff, 'month')
    if dDiff
      result.push pluralize(dDiff, 'day')
    if hourDiff
      result.push pluralize(hourDiff, 'hour')
    if minDiff
      result.push pluralize(minDiff, 'minute')
    if secDiff
      result.push pluralize(secDiff, 'second')
    result.join STRINGS.delimiter

  return

# ---
# generated by js2coffee 2.1.0
